suceess running
db success
models.py__ success
DB URI: mysql+pymysql://root:manideep@localhost/flaskdb
success
App is running fine
 * Serving Flask app 'app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
ad.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.31.38.161:80
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 124-931-458
103.252.145.45 - - [10/Apr/2025 15:02:27] "GET / HTTP/1.1" 200 -
103.252.145.45 - - [10/Apr/2025 15:02:28] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
103.252.145.45 - - [10/Apr/2025 15:02:49] "GET / HTTP/1.1" 200 -
154.81.156.10 - - [10/Apr/2025 15:17:04] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/ubuntu/Spare_Parts_TataMotors/run.py', reloading
suceess running
db success
models.py__ success
DB URI: mysql+pymysql://root:manideep@localhost/flaskdb
success
App is running fine
 * Restarting with stat
154.81.156.54 - - [10/Apr/2025 15:23:41] "GET / HTTP/1.1" 200 -
35.82.31.94 - - [10/Apr/2025 15:29:25] "GET / HTTP/1.1" 200 -
185.255.122.19 - - [10/Apr/2025 15:51:05] "GET / HTTP/1.1" 200 -
103.252.145.45 - - [10/Apr/2025 15:52:18] "GET / HTTP/1.1" 200 -
103.252.145.45 - - [10/Apr/2025 15:52:19] "GET / HTTP/1.1" 200 -
154.81.156.54 - - [10/Apr/2025 16:03:45] "GET / HTTP/1.1" 200 -
154.81.156.54 - - [10/Apr/2025 16:30:11] "GET / HTTP/1.1" 200 -
154.81.156.10 - - [10/Apr/2025 16:44:20] "GET / HTTP/1.1" 200 -
